# Generated by Django 4.1.1 on 2022-10-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=5)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('population', models.IntegerField()),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('dist', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('osm', models.CharField(max_length=15)),
                ('wikidata', models.CharField(max_length=15)),
                ('kinds', models.CharField(max_length=150)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('image', models.URLField()),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentripmap.location')),
            ],
        ),
    ]
