# Generated by Django 4.1.1 on 2022-10-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opentripmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='opentripmap.location'),
        ),
    ]
