# Generated by Django 4.1.2 on 2023-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='path',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
