# Generated by Django 4.1.2 on 2023-06-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='image',
            field=models.URLField(blank=True, default='https://source.unsplash.com/random/900x700/?person', null=True),
        ),
    ]
